export const APP_WRITE_ID = '66be7fe800302e63f628'
export const DB_ID = 'crm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'